export const WASHERWOMAN = "Washerwoman"
export const LIBRARIAN = "Librarian"
export const INVESTIGATOR = "Investigator"
export const CHEF = "Chef"
export const EMPATH = "Empath"
export const FORTUNE_TELLER = "Fortune Teller"
export const UNDERTAKER = "Undertaker"
export const MONK = "Monk"
export const RAVENKEEPER = "Ravenkeeper"
export const VIRGIN = "Virgin"
export const SLAYER = "Slayer"
export const SOLDIER = "Soldier"
export const MAYOR = "Mayor"
export const RECLUSE = "Recluse"
export const SAINT = "Saint"

